package com.test.db.test_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE RicetteBase PLEASE EDIT ../Ricette.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Ricette object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.test.db.test_db.entity.Ricette;

public class RicetteBase implements RowMapper<Ricette>{
	
	private Long _id;
	
	// Attributes
    private String Ingredienti;
    private String Nome;
    private String Procedimento;
	
	// Relations Posseduta
	private String Posseduta;
	
	
	
	@Override
	public Ricette mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Ricette obj = new Ricette();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setIngredienti(rs.getString("Ingredienti"));
			obj.setNome(rs.getString("Nome"));
			obj.setProcedimento(rs.getString("Procedimento"));
			
        	
        	// Relations 1:m Posseduta
			obj.setPosseduta(rs.getString("Posseduta"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getIngredienti() {
		return Ingredienti;
	}


	public void setIngredienti(String Ingredienti) {
		this.Ingredienti = Ingredienti;
	}
	public String getNome() {
		return Nome;
	}


	public void setNome(String Nome) {
		this.Nome = Nome;
	}
	public String getProcedimento() {
		return Procedimento;
	}


	public void setProcedimento(String Procedimento) {
		this.Procedimento = Procedimento;
	}
	
    
    // Relations 1:m Posseduta
	public String getPosseduta() {
		return Posseduta;
	}

	public void setPosseduta(String Posseduta) {
		this.Posseduta = Posseduta;
	}
    
    
    
    
}