/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE userBaseService PLEASE EDIT ../user.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { User } from '../../domain/test_db/user';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../User.service.ts
 */

/*
 * SCHEMA DB User
 *
	{
		password: {
			type: 'String',
			required : true
		},
		username: {
			type: 'String',
			required : true,
			unique : true, 
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Posseduta: {
			type: Schema.ObjectId,
			ref : "Ricette"
		},
	}
 *
 */
@Injectable()
export class UserBaseService {

    contextUrl: string = environment.endpoint + '/Users';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * UserService.get
    *   @description CRUD ACTION get
    *   @returns User
    *
    */
    get(id: string): Observable<User> {
        return this.http
            .get<User>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * UserService.update
    *   @description CRUD ACTION update
    *   @returns User
    *
    */
    update(item: User): Observable<User> {
        return this.http
            .post<User>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
